### ISSUE TITLE
Connect Choregraphe to qibullet

### ISSUE THREAD

**Issue by m0rph03nix** [softbankrobotics-research/qibullet#14]
Thanks for qibullet. Great job. Is there a way to connect Choregraphe to the naoqi instance of the simulation ? Or in the other way around, is there a way to launch a simulation on an existing naoqi instance. Thank you in advance

**Comment by m0rph03nix** [comment]
... I see in the code there is no naoqi behind. :'( So I've got my answer !

**Comment by mcaniot** [comment]
Hi ! You can't connect Choregraphe with qibullet. What do you want to do with Choregraphe ? If you want to run some naoqi function on the simulated robot, the qibullet API is closed to the NAOqi one. For example, the function moveTo is implemented like the NAOqi one in qibullet.

**Comment by m0rph03nix** [comment]
Yes I realized it in the code just before your answer. Actually my need is not Choregraphe but to run Behaviours with other AL"Stuff" like ALDialog

**Comment by mcaniot** [comment]
Alright, I get it. Right now, the simulation is focused on physical interaction and navigation. There is no feature like dialog or human interaction for the moment.

**Comment by Pandhariix** [comment]
Like @mcaniot said, we are mostly focused on implementing "low level" features of the NAOqi API (what could could find in ALMotion or in ALVideoDevice for instance).

That being said, you could very well launch a qibullet simulation from a Choregraphe project, and design a wrapper connecting a virtual Choregraphe robot to the qibullet one

**Comment by m0rph03nix** [comment]
Thanks ! I will do that and share when I'll find the time.

**Comment by mbusy** [comment]
Hi @m0rph03nix, any updates, did you manage to make it work ?

**Comment by m0rph03nix** [comment]
Hi @mbusy. I started something last year... but stopped at an early state... lack of time. I'll let you know if I do something more

**Comment by mbusy** [comment]
Alright! In that case I'll close the issue for now, feel free to re-open it (or open a new one) if you need specifications or wish to share something new. Take care !
