### ISSUE TITLE
Update robot meshes

### ISSUE THREAD

**Issue by m0rph03nix** [softbankrobotics-research/qibullet#16]
Hi again,
Is it planned to commit the authentic meshes of the robot ?
Thank you

**Comment by Pandhariix** [comment]
Hi,

Yes we eventually want to have a virtual model as close as possible from the real one, updating the meshes of the model will greatly improve this resemblance

**Comment by mbusy** [comment]
Updated meshes for the Pepper robot have been released in [v1.4.0](https://github.com/softbankrobotics-research/qibullet/releases/tag/1.4.0)
