### ISSUE TITLE
QiSDK Pepper 2.5.* ( API Level 6 ) - compatible?

### ISSUE THREAD

**Issue by pzarzycki** [softbankrobotics-research/qibullet#34]
Great Project!
I have a kind question regarding compatibility with physical robots (Pepper):
In your documentation it is mentioned "The Python API allowing to interact with a virtual robot is voluntarily close to the one provided by the NAOqi framework  (2-5)"

What about QiSDK API Level 6? Recent versions of Pepper 2.5.*.* (the one we have at the Uni) are no longer accessible via Choreographe. We were using QiSDK for Android so far.
**System version:**
Robot : Robot pepper (AP990397A04P69Mxxxxx)
Type : Release
Version : 2.5.10.7

![image](https://user-images.githubusercontent.com/3589204/81985662-d9851780-9636-11ea-80e3-2e10d2b69a58.png)

**Comment by mbusy** [comment]
Thanks!

I'm not sure that I fully understand your question, do you want to know if the qiBullet API will one day be similar to the QiSDK one ? If so, my answer is probably not.

The QiSDK is designed to interact with the robot from an Android activity, and really focuses on human robot interactions / high level behaviours.
qiBullet on the other hand really focuses on "lower level tasks", and can be used to test navigation techniques, grasping techniques, perform reinforcement learning, etc. The simulator is not (at least in its current form) really ideal to perform human robot interaction tasks.

**Comment by mbusy** [comment]
Hi @pzarzycki, does that answer your question ?

**Comment by mbusy** [comment]
I'll close the issue for now. Feel free to reopen it if you have additional questions on the subject!
