### ISSUE TITLE
Depth camera doesn't see robot's own joints

### ISSUE THREAD

**Issue by wagenaartje** [softbankrobotics-research/qibullet#38]
I'm not sure if this is intended behaviour, but the depth camera does not see the robot's hands for instance.

**Comment by mbusy** [comment]
Hi @wagenaartje, I'm pretty sure that the near plane of the depth camera is responsible for that behaviour. With Pepper's depth camera (on Pepper < 1.8), the minimum detection distance is 40cm.

So if an object is less than 40cm away from the camera, it won't be detected. In the code, we mimic that behaviour by setting the near plane of the virtual depth camera ([depth camera definition](https://github.com/softbankrobotics-research/qibullet/blob/bcd8c5dea46a6932f1158770c7b58dd31b569985/qibullet/camera.py#L503), instantiation in [pepper_virtual](https://github.com/softbankrobotics-research/qibullet/blob/bcd8c5dea46a6932f1158770c7b58dd31b569985/qibullet/pepper_virtual.py#L147-L153))

If you want to set a custom near plane, you could either:
* Clone the repo, modify the near plane value when creating the camera in pepper_virtual, and install this custom qibullet package on your computer
* Directly update the near plane of the camera from your code, accessing to the `near_plane` field of the depth camera object
