### ISSUE TITLE
Stopping an asynchronous movement

### ISSUE THREAD

**Issue by wagenaartje** [softbankrobotics-research/qibullet#40]
During an asynchronous `moveTo` movement, I want to launch a synchronous movement. This gives the error:

```python
pybullet.error: Already a moveTo asynchronous. Can't launch moveTo synchronous
```

However, is there a way to stop the current asynchronous movement so that a synchronous movement can be performed?

**Comment by wagenaartje** [comment]
Update: I found a work-around for now,

```python
pepper_pos = pepper.getPosition();
pepper.moveTo(0, 0, 0, frame=PepperVirtual.FRAME_ROBOT, speed=1, _async=True)
time.sleep(0.5)
```

Basically, it preforms an asynchronous movement to the current position which is quickly stopped. I'm still curious if there is a cleaner way, for example some kind of `pepper.stop()` function.

**Comment by mbusy** [comment]
That's indeed the solution you should use for now. But that's a great point, a `stopMove` methods along the lines of the one defined in the [ALMotion documentation](http://doc.aldebaran.com/2-5/naoqi/motion/control-walk-api.html#ALMotionProxy::stopMove) would be a great add-on
