### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by wagenaartje** [softbankrobotics-research/qibullet#43]
There is a small typo in the [documentation](https://softbankrobotics-research.github.io/qibullet/api/classqibullet_1_1simulation__manager_1_1SimulationManager.html#aeac971c9a89aab4625031beb947cc088) for the `spawnPepper`, `spawnNao` and `spawnRomeo` functions. The functions themselves use `quaternion` as an argument, but in the description of the parameters, `quaternions` is used (with an extra "s").

**Comment by mbusy** [comment]
Well spotted :+1:
