### ISSUE TITLE
Segmentation fault (core dumped) when I accept the LICENSE and install the meshes and URDFs

### ISSUE THREAD

**Issue by xiejialong** [softbankrobotics-research/qibullet#70]
###########################################################
| You must accept the license to install the robot meshes. |
###########################################################
Accept (y/n)? y
Segmentation fault (core dumped)

**Comment by mbusy** [comment]
@xiejialong Any updates on the above comment? Did you manage to solve your problem?

**Comment by mbusy** [comment]
@xiejialong I will close the issue for now, don't hesitate to reopen it if you still encounter the problem
