### ISSUE TITLE
bad magic number for the meshes installer

### ISSUE THREAD

**Issue by lpwwpl** [softbankrobotics-research/qibullet#71]
when i run examples, errors ocur

  File "C:\Users\86135\Desktop\qibullet-master\qibullet\tools.py", line 139, in _install_resources
    import meshes_installer_38 as meshes_installer
ImportError: bad magic number in 'meshes_installer_38': b'vers'

**Comment by mbusy** [comment]
Hi, which Python version are you using? This error occurs when no installer is found for the used Python version

**Comment by mbusy** [comment]
It could also be a git LFS problem, please see issue #48

**Comment by mbusy** [comment]
@lpwwpl Any updates on that issue ?

**Comment by lpwwpl** [comment]
> @lpwwpl Any updates on that issue ?

good,it takes effect。

**Comment by mbusy** [comment]
Perfect, I'll close the issue then
