### ISSUE TITLE
pepper_shadowing 

### ISSUE THREAD

**Issue by ysys98** [softbankrobotics-research/qibullet#76]
when I rosrun pepper_shadowing.py
In fact, I replaced pepper with Nao, and then this result occurred. 
At first, I thought it could not be replaced, 
but this result also occurred when I ran the code before replacement
<img width="674" alt="shadowing" src="https://user-images.githubusercontent.com/98088332/158759966-178d325b-e85b-417d-a480-e5e178393e63.png">

what should I do ？

**Comment by mbusy** [comment]
Hi @ysys98, you can indeed replace Pepper with NAO in the example, more specifically by modifying [this line](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L37). But the example doesn't use ROS, it directly uses the qi SDK to interact with the robot (as you can see [here](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L27-L32)). I would advise to launch the program without rosrun:
```bash
# replace the x.x.x.x by the ip of the real robot
python pepper_shadowing.py --ip x.x.x.x
```

You probably got the error message because you didn't specify the ip of your robot

**Comment by ysys98** [comment]
> Hi @ysys98, you can indeed replace Pepper with NAO in the example, more specifically by modifying [this line](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L37). But the example doesn't use ROS, it directly uses the qi SDK to interact with the robot (as you can see [here](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L27-L32)). I would advise to launch the program without rosrun:
> 
> ```shell
> # replace the x.x.x.x by the ip of the real robot
> python pepper_shadowing.py --ip x.x.x.x
> ```
> 
> You probably got the error message because you didn't specify the ip of your robot
@mbusy thank you a lot ！
and I am a novice student, so thank you for taking the trouble to solve these very simple problems for me. I just saw you in Naoqi_ Driver's reply to me, which is what bothers me. I downloaded qibullet according to the tutorial, so I have to say that Ubuntu already exists ROS_ Wrapper.py，And I checked it
<img width="476" alt="1" src="https://user-images.githubusercontent.com/98088332/158857996-1bc574dc-6921-4e4d-a4c2-5a913685f77a.png">
, all I do is run the code like examples, but I run the robot_ ros_ test. After py, whether I run rosrun rviz rviz directly on the terminal 
<img width="1141" alt="2" src="https://user-images.githubusercontent.com/98088332/158858065-6e72e45d-581e-4753-b0b4-39dcd3551bee.png">
or I run the launch file that starts rviz in vscode，I can't find odmo in the Fixed Frame. I'm quite confused
<img width="1146" alt="3" src="https://user-images.githubusercontent.com/98088332/158858144-2e164bf2-394f-4c35-a632-a541c326d45e.png">

**Comment by ysys98** [comment]
> Hi @ysys98, you can indeed replace Pepper with NAO in the example, more specifically by modifying [this line](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L37). But the example doesn't use ROS, it directly uses the qi SDK to interact with the robot (as you can see [here](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L27-L32)). I would advise to launch the program without rosrun:
> 
> ```shell
> # replace the x.x.x.x by the ip of the real robot
> python pepper_shadowing.py --ip x.x.x.x
> ```
> 
> You probably got the error message because you didn't specify the ip of your robot

@mbusy The same problem also appears in Pepper , when I run the robot_ ros_ test. py, load rviz through the launch file. Similarly, there is no Odom in the Fixed Frame in pepper's rviz, and there is a base_ footprint in Fixed Frame , I remember that base_footprint link should be  written in pepper.urdf
<img width="1197" alt="110" src="https://user-images.githubusercontent.com/98088332/158930513-550bea79-82cf-414b-a911-a885d9efd3c6.png">

**Comment by ysys98** [comment]
@mbusy Thank you very much! I have followed your reply to do things about  [https://github.com/ros-naoqi/naoqi_driver/issues/147](url)
when I  added _ broadcastodometry method into robot_ ros_ test. py, I made an error after the operation. I checked and found that I may not have a publisher about odometry, so I found a odometry_ publisher.cpp program that might provide a publisher  at [http://docs.ros.org/en/kinetic/api/odometry_publisher_tutorial/html/odometry__publisher_8cpp_source.html](url)
, I think I have one parameter of _broadcastodometry (def _broadcastodometry (self, odometry_publisher):), but when I run odometry_ publisher. cpp to start the publisher of odometry and run the robot_ ros_ test. py I modified, but he automatically closes it and outputs such a log:
Traceback (most recent call last):
  File "/home/roskinetic/demo01_ws/src/qibullet/scripts/robot_ros_test.py", line 50, in <module>
    wrap._broadcastOdometry("odom_pub")
  File "/home/roskinetic/.local/lib/python2.7/site-packages/qibullet/ros_wrapper.py", line 208, in _broadcastOdometry
    physicsClientId=self.robot.getPhysicsClientId())
TypeError: function takes at most 2 arguments (3 given)
Stopping the ROS wrapper: function takes at most 2 arguments (3 given)
[robot_state_publisher_roskinetic_VirtualBox_21246_1218137726150742084-1] killing on exit
[WARN] [1647703861.872514]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
Stopping roslauncher
This is the odometry_ publisher.cpp I found, the robot_ ros_ test. py I modified, and his input log：
<img width="573" alt="7" src="https://user-images.githubusercontent.com/98088332/159129528-56a1e77d-7799-451a-8053-1121566034f1.png">
<img width="509" alt="8" src="https://user-images.githubusercontent.com/98088332/159129531-c977c056-4690-46ea-bc26-a44cd408bd85.png">


<img width="583" alt="4" src="https://user-images.githubusercontent.com/98088332/159129462-e0a0198e-c1c4-4f1b-af34-75e0b8b8920c.png">
<img width="711" alt="6" src="https://user-images.githubusercontent.com/98088332/159129470-09b54e7d-7ee6-495d-8633-085d9ccae761.png">

<img width="718" alt="1" src="https://user-images.githubusercontent.com/98088332/159129447-eee9a899-b693-4561-995f-d10d3a7f186b.png">
<img width="785" alt="5" src="https://user-images.githubusercontent.com/98088332/159129456-8001a43f-4e0f-47b8-8630-a7dd1081187e.png">

**Comment by ysys98** [comment]
> Hi @ysys98, you can indeed replace Pepper with NAO in the example, more specifically by modifying [this line](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L37). But the example doesn't use ROS, it directly uses the qi SDK to interact with the robot (as you can see [here](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L27-L32)). I would advise to launch the program without rosrun:
> 
> ```shell
> # replace the x.x.x.x by the ip of the real robot
> python pepper_shadowing.py --ip x.x.x.x
> ```
> 
> You probably got the error message because you didn't specify the ip of your robot
@mbusy Thank you very much! I have followed your reply to do things about  [https://github.com/ros-naoqi/naoqi_driver/issues/147](url)
when I  added _ broadcastodometry method into robot_ ros_ test. py, I made an error after the operation. I checked and found that I may not have a publisher about odometry, so I found a odometry_ publisher.cpp program that might provide a publisher  at [http://docs.ros.org/en/kinetic/api/odometry_publisher_tutorial/html/odometry__publisher_8cpp_source.html](url)
, I think I have one parameter of _broadcastodometry (def _broadcastodometry (self, odometry_publisher):), but when I run odometry_ publisher. cpp to start the publisher of odometry and run the robot_ ros_ test. py I modified, but he automatically closes it and outputs such a log:
Traceback (most recent call last):
  File "/home/roskinetic/demo01_ws/src/qibullet/scripts/robot_ros_test.py", line 50, in <module>
    wrap._broadcastOdometry("odom_pub")
  File "/home/roskinetic/.local/lib/python2.7/site-packages/qibullet/ros_wrapper.py", line 208, in _broadcastOdometry
    physicsClientId=self.robot.getPhysicsClientId())
TypeError: function takes at most 2 arguments (3 given)
Stopping the ROS wrapper: function takes at most 2 arguments (3 given)
[robot_state_publisher_roskinetic_VirtualBox_21246_1218137726150742084-1] killing on exit
[WARN] [1647703861.872514]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
Stopping roslauncher
This is the odometry_ publisher.cpp I found, the robot_ ros_ test. py I modified, and his input log：
<img width="573" alt="7" src="https://user-images.githubusercontent.com/98088332/159129528-56a1e77d-7799-451a-8053-1121566034f1.png">
<img width="509" alt="8" src="https://user-images.githubusercontent.com/98088332/159129531-c977c056-4690-46ea-bc26-a44cd408bd85.png">


<img width="583" alt="4" src="https://user-images.githubusercontent.com/98088332/159129462-e0a0198e-c1c4-4f1b-af34-75e0b8b8920c.png">
<img width="711" alt="6" src="https://user-images.githubusercontent.com/98088332/159129470-09b54e7d-7ee6-495d-8633-085d9ccae761.png">

<img width="718" alt="1" src="https://user-images.githubusercontent.com/98088332/159129447-eee9a899-b693-4561-995f-d10d3a7f186b.png">
<img width="785" alt="5" src="https://user-images.githubusercontent.com/98088332/159129456-8001a43f-4e0f-47b8-8630-a7dd1081187e.png">

**Comment by ysys98** [comment]
> Hi @ysys98, you can indeed replace Pepper with NAO in the example, more specifically by modifying [this line](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L37). But the example doesn't use ROS, it directly uses the qi SDK to interact with the robot (as you can see [here](https://github.com/softbankrobotics-research/qibullet/blob/fd9284072221a87801ba1ab4490d2fdbb15bc933/examples/pepper_shadowing.py#L27-L32)). I would advise to launch the program without rosrun:
> 
> ```shell
> # replace the x.x.x.x by the ip of the real robot
> python pepper_shadowing.py --ip x.x.x.x
> ```
> 
> You probably got the error message because you didn't specify the ip of your robot

@mbusy When I checked, I found that vscode did not display the import pybullet module. I thought it might be that it was not installed properly during installation, so I reinstalled it again and solved this problem.
 For the above problems, I'm made a small change for ros_ wrapper. py , 
<img width="519" alt="333" src="https://user-images.githubusercontent.com/98088332/159327000-c4b36d54-7e20-4dde-ae04-13f9068a1fda.png">
Oh, by the way, I changed the parameters above wrap._broadcastOdometry("odom_pub") from odometry_publisher to odom_pub,
<img width="451" alt="444" src="https://user-images.githubusercontent.com/98088332/159327356-abced361-16b7-4a32-863f-d39fbaa87a52.png">
After I ran it, although it did not close automatically, an error log still appeared
<img width="275" alt="555" src="https://user-images.githubusercontent.com/98088332/159327517-617696c8-cd27-4568-ae72-858183fead46.png">
