### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by johann-petrak** [softbankrobotics-research/qibullet#85]
When browsing the wiki and API documentation:

* The links from the wiki to the API documentation are broken: https://softbankrobotics-research.github.io/qibullet/api/ gives a 404
* the API docs are apparently: https://softbankrobotics-research.github.io/qibullet/annotated.html
* The documentation for the setAngles method for RobotVirtual says the values should be between 0 and 1, but the documentation for the setAngles method for PepperVirtual says it should be a percentage (which would mean between 0.0 and 100.0). The corresponding naoqi API requires a value between 0 and 1 there though so what is it for the PepperVirtual class?
* The documentation does not say anything about error handling or debugging

**Comment by mbusy** [comment]
* The link towards the documentation has been updated in the wiki.
* Regarding the documentation for the `setAngles` method, both methods specify a percentage, the only difference is that the base method defined in RobotVirtual specifies that the value is expected to be between 0 and 1. The method defined in PepperVirtual also expects percentages, so the same kind of value (for instance 50%, or 0.5, will be comprised between 0 and 1 :grin:) If it wasn't explicit enough, now it will be, the value range has been specified in the various setAngles methods.
* There is no plan to add anything about error handling and debugging in the docs. But if you want to add that, PRs are welcome!
