### ISSUE TITLE
Error during Installing resources for qiBullet

### ISSUE THREAD

**Issue by Gamdschi** [softbankrobotics-research/qibullet#90]
I tried the usage example, after accepting the END USER LICENSE AGREEMENT i receive the following error:

> Traceback (most recent call last):
>   File "/Users/$user/PycharmProjects/pythonProject/main.py", line 17, in <module>
>     pepper = simulation_manager.spawnPepper(
>   File "/Users/$user/PycharmProjects/pythonProject/.venv/lib/python3.9/site-packages/qibullet/simulation_manager.py", line 194, in spawnPepper
>     pepper_virtual = PepperVirtual()
>   File "/Users/$user/PycharmProjects/pythonProject/.venv/lib/python3.9/site-packages/qibullet/pepper_virtual.py", line 38, in __init__
>     tools._install_resources()
>   File "/Users/$user/PycharmProjects/pythonProject/.venv/lib/python3.9/site-packages/qibullet/tools.py", line 168, in _install_resources
>     if meshes_installer._install_meshes(resources_folder, agreement=agreement):
>   File "obfuscated_installer.py", line 170, in _install_meshes
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1257, in __init__
>     self._RealGetContents()
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file

My OS is macOS Sonoma 14.1 (23B74) and I am using python 3.9

**Comment by mbusy** [comment]
Hi, I assume that you tried to install the project from source? This error could be due to git-lfs not being installed when you clone the repo.

Could you install git-lfs with apt, go to the repository and call `git lfs pull` as specified in the wiki?

You also might have additional issues when running the sim, due to the fact that you're using macos

**Comment by Gamdschi** [comment]
t
